name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'api/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'api/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      working-directory: ./api/MemoryGameApi
      run: dotnet restore
    
    - name: Build API
      working-directory: ./api/MemoryGameApi
      run: dotnet build --no-restore --configuration Release
    
    - name: Run API Tests
      working-directory: ./api/MemoryGameApi.Tests
      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./api/MemoryGameApi.Tests/TestResults
        flags: backend
        name: backend-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}