name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/memory-game/package-lock.json
    
    - name: Install dependencies
      working-directory: ./frontend/memory-game
      run: npm ci
    
    - name: Lint code
      working-directory: ./frontend/memory-game
      run: npm run lint --if-present
    
    - name: Run tests
      working-directory: ./frontend/memory-game
      run: npm test -- --coverage --watchAll=false
      env:
        CI: true
    
    - name: Build application
      working-directory: ./frontend/memory-game
      run: npm run build
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./frontend/memory-game/coverage
        flags: frontend
        name: frontend-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./frontend/memory-game/build/